library(parallel)
library(brms)
library(bayesplot)
library(gridExtra)
library(dplyr)
library(ggplot2)
library(dplyr)
library(rstan)

options(mc.cores = parallel::detectCores())
options(brms.backend = "rstan")
setwd("/home/control/yimzha/Documents/fits")

load("fit_1.RData")
summary(fit_1)
